// <auto-generated />
namespace TheGathering.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MealSiteActivation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MealSiteActivation));
        
        string IMigrationMetadata.Id
        {
            get { return "202007301856235_MealSiteActivation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
